# Generated by Django 5.2.7 on 2026-09-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='rack_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='retail_price',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
