# Generated by Django 5.2.7 on 2026-09-21 06:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_fuelstation_rack_id_alter_fuelstation_retail_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('start_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('start_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destination_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destination_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('total_distance_miles', models.FloatField()),
                ('starting_fuel', models.FloatField()),
                ('current_fuel', models.FloatField()),
                ('current_route_mile', models.FloatField(default=0)),
                ('total_fuel_purchased', models.FloatField(default=0)),
                ('total_money_spent', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefuelingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_mile', models.FloatField()),
                ('gallons', models.FloatField()),
                ('price_per_gallon', models.DecimalField(decimal_places=6, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fuel_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuel.fuelstation')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refueling_events', to='fuel.trip')),
            ],
        ),
    ]
