# Generated by Django 5.2.7 on 2026-09-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_trip_refuelingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='fuel_stations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='recommended_stops',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='route_geometry',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_fuel',
            field=models.FloatField(default=0),
        ),
    ]
